<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keluar</name>
   <tag></tag>
   <elementGuidId>a8b0922e-567b-4a95-ba7f-efdd1b27a9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Keluar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-flat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db0c5beb-10dc-4693-a3f3-b3229c1d8f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mngr.dbo.id/auth/logout</value>
      <webElementGuid>f98c1657-b4a0-49f6-bdaf-70bf276d5a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-flat</value>
      <webElementGuid>a6f99189-fb96-42bb-a02c-8952fba33b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>c9a583c3-8d13-495e-a7af-4c899482e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-black sidebar-mini      pace-done&quot;]/div[@class=&quot;wrapper&quot;]/header[@class=&quot;main-header&quot;]/nav[@class=&quot;navbar navbar-static-top&quot;]/div[@class=&quot;navbar-custom-menu&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown user user-menu open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;user-footer&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;pull-right&quot;]/a[@class=&quot;btn btn-danger btn-flat&quot;]</value>
      <webElementGuid>eae07802-9865-425e-9fee-2957828f3ba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>bd741652-8d6c-4e79-b581-246f463e7c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ginda MU DBO'])[1]/following::a[1]</value>
      <webElementGuid>dfa87817-9541-44f6-89f0-8c3f4727a8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEM'])[1]/preceding::a[1]</value>
      <webElementGuid>ad3bb066-7b9e-4e89-be1b-ad0ea30fe51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dasbor'])[1]/preceding::a[1]</value>
      <webElementGuid>b5deb459-01bb-4e4b-a161-d69df34574f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>6db68c5c-7e61-4688-801d-f62ef690611c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mngr.dbo.id/auth/logout')]</value>
      <webElementGuid>ccdeb095-90b3-41e9-9642-4cd2f67fb525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>160f2d06-9532-4166-b4a8-fe4ac607de81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mngr.dbo.id/auth/logout' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>652f5b61-dd4c-4961-9f82-dcafa0b5fcb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
