<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_lbr</name>
   <tag></tag>
   <elementGuidId>a3fb9dc1-10aa-4728-acbd-089417808c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;satuan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b0957e6-bd7e-423d-9b16-9c6e5601de2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>satuan</value>
      <webElementGuid>43017364-4c85-4cae-b2ab-005846b47175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control paddingzero</value>
      <webElementGuid>cb7678b1-cb90-477e-bba4-b171ef49804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        lbr
                                                      </value>
      <webElementGuid>8cbe2583-25ce-4a1d-94b0-1a71a351b019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;katalog&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel panel-danger&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[1]/td[11]/select[@class=&quot;form-control paddingzero&quot;]</value>
      <webElementGuid>2478babc-09c0-4322-9bb8-a7e3cd0d4ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id=''])[2]</value>
      <webElementGuid>622264f8-b92e-4163-aad3-d1a27fd477f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[2]/div/div[2]/div[2]/div/div/table/tbody/tr/td[11]/select</value>
      <webElementGuid>3c46bd3b-3304-4f95-9a55-20335702c6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp.'])[1]/following::select[1]</value>
      <webElementGuid>e222b673-1fe8-4203-b966-6d8133c5af7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(lbr)'])[1]/following::select[1]</value>
      <webElementGuid>46a116ac-26be-4ff4-9531-a2b02c2be448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Djabesmen'])[3]/preceding::select[1]</value>
      <webElementGuid>e0fe46af-84b5-451e-810c-0a1a1186f236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Djabes 11'])[2]/preceding::select[1]</value>
      <webElementGuid>4f6dff0c-20d2-4ad7-ba14-2e529953a2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/select</value>
      <webElementGuid>604b8044-6806-4edf-ae08-2d87865d6157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'satuan' and (text() = '
                                                        lbr
                                                      ' or . = '
                                                        lbr
                                                      ')]</value>
      <webElementGuid>4ec7e800-e22b-48ee-a2d0-9e588343528b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
