<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insentif Salesman 2.0</name>
   <tag></tag>
   <elementGuidId>07678924-8b68-43e4-ae4b-937437d4681b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-salesmanSelect-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-salesmanSelect-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e4eb304-8c49-493c-9f72-dc6f6227b320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>809989db-492b-4627-bf15-3461a0123a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-salesmanSelect-container</value>
      <webElementGuid>4693c7d8-b0f0-4fa0-b853-6a188a0f1854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>966bc462-158b-476c-bf92-133825618767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc2d6740-02ce-4ec0-ab44-463b3a054bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Insentif Salesman 2.0</value>
      <webElementGuid>8ba41fc9-ce23-4f14-a4cc-eff823cc3e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insentif Salesman 2.0</value>
      <webElementGuid>d9724214-4ce4-4991-b925-915115b26741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-salesmanSelect-container&quot;)</value>
      <webElementGuid>982a8620-637a-4b56-a9ff-a91ec971035b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-salesmanSelect-container']</value>
      <webElementGuid>302d1943-b383-4899-8910-52d2d42d8144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formProcess']/div/div[2]/div/div[2]/div/div[2]/div/span/span/span/span</value>
      <webElementGuid>92928c0a-1ba4-404a-8a71-a98113a80bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesman'])[2]/following::span[4]</value>
      <webElementGuid>20001728-fa59-4941-8fa6-48a4a04a6a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary Order'])[1]/following::span[4]</value>
      <webElementGuid>6c66025b-8ea2-4407-8f79-926b29ddeba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[1]/preceding::span[3]</value>
      <webElementGuid>9c48e95b-ab63-4245-9d06-99ff369b6603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/preceding::span[3]</value>
      <webElementGuid>3d64573d-ea3a-44c0-a9dd-34e20983efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>c3495ffb-66b6-48d3-bdc2-b77d322fcddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-salesmanSelect-container' and @title = 'Insentif Salesman 2.0' and (text() = 'Insentif Salesman 2.0' or . = 'Insentif Salesman 2.0')]</value>
      <webElementGuid>5172fbe7-8766-49c8-a84e-f52c1ed17820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
