<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari</name>
   <tag></tag>
   <elementGuidId>8a429f30-0f6b-45d5-85a0-d49418c23dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-filter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbc126ec-452d-4734-b306-1173623550c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-filter</value>
      <webElementGuid>e90d7ebb-59e4-4e58-805c-58f619ef1e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-rounded btn-primary</value>
      <webElementGuid>61dc5966-1280-482a-abe9-6c99b6b60d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Cari
                                        </value>
      <webElementGuid>4ccce4ac-0ac9-4ceb-ad88-903730db4351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-filter&quot;)</value>
      <webElementGuid>369ee701-240b-4e7c-af24-c9581ec8a1be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-filter']</value>
      <webElementGuid>06e0dd52-4b7f-4b29-96b6-b797307226d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseExample']/div/div/div[2]/div/div[3]/button</value>
      <webElementGuid>9293d795-6353-4d47-a6c2-e3207ad9b35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/following::button[1]</value>
      <webElementGuid>51859fc5-7fc1-4bd3-898c-925d70613226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::button[1]</value>
      <webElementGuid>d9fd110f-dcfe-4533-b680-55547b199395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button</value>
      <webElementGuid>bd612456-a22a-44db-ae2c-10b5643acc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submit-filter' and (text() = '
                                             Cari
                                        ' or . = '
                                             Cari
                                        ')]</value>
      <webElementGuid>0ef7c5fb-b330-42a6-abb5-d5b93ab02fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
