<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Toko_store_code</name>
   <tag></tag>
   <elementGuidId>e07cf7bd-a9e4-4ca7-9711-3114be7ecf57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='store_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#store_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d72fdd9c-5445-42f5-9b32-5df0e17457bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-3 form-control form-group</value>
      <webElementGuid>9cb1c618-90c6-4767-9b3e-6fa1fd0a39dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Toko</value>
      <webElementGuid>b946e78c-c16a-4149-8de6-716dd3617377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>store_code</value>
      <webElementGuid>a3bb93ea-7891-4860-a12f-3f8d380aeed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afeaac5d-2c44-4214-9d08-39ff83f92769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>store_code</value>
      <webElementGuid>eb68a058-02f4-4d09-853c-4004a9a3cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store_code&quot;)</value>
      <webElementGuid>0fcbea6a-6be8-46c5-a8c8-a59723ec59e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='store_code']</value>
      <webElementGuid>72f09183-7122-48e6-978f-486c5b69b0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-advance-filter']/div[2]/div/div/div/div/div[4]/input</value>
      <webElementGuid>46886168-0166-4d30-a2f8-9244061a6071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>65aaa022-fabd-4ee9-85ec-d99f1cbf39ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Kode Toko' and @name = 'store_code' and @type = 'text' and @id = 'store_code']</value>
      <webElementGuid>d9e45bfa-b423-4de8-a889-fe25c6ab9d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
