<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status order</name>
   <tag></tag>
   <elementGuidId>ab16fe8d-cf28-4541-b29d-c8eb8109f173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status_order']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2720ebf-15ad-47e9-86d8-59a1e2203617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>085fe41a-c7fc-43d0-bd60-ed0ddd11676f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_order</value>
      <webElementGuid>264eca77-fbd4-436d-a06f-bd4223d290c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_order</value>
      <webElementGuid>628ab08f-0630-420d-8c3b-43854e70cf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>allpendingrejectopenpartialclosecanceled</value>
      <webElementGuid>0ceb1f37-9d79-49f4-8316-56ac658b1aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status_order&quot;)</value>
      <webElementGuid>6d8b5c86-45db-415b-9cdb-a7dfc25e0003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status_order']</value>
      <webElementGuid>ffc1ffbb-fe53-4f5e-bd5e-28cfb285fbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-advance-filter']/div[2]/div/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>933f1921-f381-4ccc-9265-266386e5fd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Order'])[1]/following::select[1]</value>
      <webElementGuid>5689d76e-09ff-42df-ba89-f745b92a29ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral Order'])[1]/following::select[1]</value>
      <webElementGuid>cfed7094-f9a9-42ba-a4b3-cd351196bf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Via'])[1]/preceding::select[1]</value>
      <webElementGuid>fe29e004-4732-4322-bfe2-75ddf998743a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Toko'])[1]/preceding::select[2]</value>
      <webElementGuid>6acebdc2-79be-47d0-ab9a-e5bec42b6fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>88c9a8b2-8f17-477e-a2c8-e6932e96ab75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status_order' and @name = 'status_order' and (text() = 'allpendingrejectopenpartialclosecanceled' or . = 'allpendingrejectopenpartialclosecanceled')]</value>
      <webElementGuid>4b366058-20f1-4afb-aab6-a89d0dccae8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
